services:
  postgres:
    image: postgres:15-alpine
    container_name: medusa_postgres_prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - medusa_network

  redis:
    image: redis:7-alpine
    container_name: medusa_redis_prod
    restart: unless-stopped
    networks:
      - medusa_network

  medusa:
    image: ghcr.io/calumbradley/bradleyco/medusa:latest
    container_name: medusa_backend_prod
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://medusa:medusa@postgres:5432/medusa
      - REDIS_URL=redis://redis:6379
    # no bind mounts in prod so image contains the code and Dockerfile CMD runs ./start.sh
    networks:
      - medusa_network

volumes:
  postgres_data_prod:

networks:
  medusa_network:
    driver: bridge
