name: Deploy to Droplet

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.DO_SSH_PORT || '22' }}
          script: |
            set -e
            mkdir -p "${{ secrets.REPO_PATH }}"
            cd "${{ secrets.REPO_PATH }}"

            # ensure github.com is in known_hosts to avoid "Host key verification failed"
            mkdir -p ~/.ssh
            grep -q github.com ~/.ssh/known_hosts || ssh-keyscan github.com >> ~/.ssh/known_hosts

            if [ ! -d .git ]; then
              git clone -b "${{ secrets.BRANCH }}" git@github.com:calumbradley/bradleyco.git .
            else
              git fetch --all
              git reset --hard origin/"${{ secrets.BRANCH }}"
            fi
            docker compose -f docker-compose.prod.yml pull || true
            docker compose -f docker-compose.prod.yml up -d --build
